name: 'Hello World'
description: 'Sql filde checker.'
inputs:
  new-migrations:  # id of input
    description: 'New migrations files'
    required: true

  new-seeders:  # id of input
    description: 'New seeders files'
    required: true

  dir:  # id of input
    description: 'path to files.'
    required: true

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'index.js'
