name: 'SQL file validator'
description: 'Validates if the SQL files pushed in the PR meet the necessary standard.'
inputs:
  new-migrations:  # Migrations files with changes.
    description: 'New migrations files'
    required: true

  new-seeders:  # Seeders files with changes.
    description: 'New seeders files'
    required: true

  dir:  # Root of the new or changed files.
    description: 'path to files.'
    required: true

  feature-flag:  # Feature flag to enable the validator.
    description: 'Feature flag to enable the exit action for the Workflow.'
    required: true
    default: 'false'

  token:  # token from github
    description: 'token from github'
    required: true

  pass-emoji:  # emoji when the validator pass.
    description: 'emoji when the validator pass'
    required: true

  fail-emoji:  # emoji when the validator fails.
    description: 'emoji when the validator fails'
    required: true

  job-url:  # url of the job.
    description: 'url of the job'
    required: true

outputs:
  successful-validation: # Validation Status.
    description: 'Status of the files validation.'
runs:
  using: 'node20'
  main: 'index.js'
